### ISSUE TITLE
Option to reverse changes

### ISSUE THREAD

**Issue by V7899** [Scrut1ny/Windows-Debloating-Script#1]
Please add an option to reverse all changes back to how it was before the debloat, I want to reverse it back and everything is ruined at the moment. All my desktop items have been deleted, so much has been lost

**Comment by Neoncat-OG** [comment]
Yeah it ruined my headphones. Now they will not connect. Please add this option.

**Comment by Scrut1ny** [comment]
I do not understand how it ruined your headphones, the script has nothing to do with that.

**Comment by Neoncat-OG** [comment]
It turns out it was not your script unless it has something to do with disabling notifications. I reinstalled windows and everything worked

**Comment by Scrut1ny** [comment]
Man you didn't need to reinstall Windows for that one small easily fixable issue, my script does disable notifications and some other stuff in the windows settings, I still don't understand why it effected your headphones... What headphones do you even have and are you using BT or a wired connection?

**Comment by Neoncat-OG** [comment]
Sorry I am replying so late but they were wired headphones and in order to correctly pair them I had to click on a confirmation notification. I tried reversing the notification changes of your script manually with no luck. But It may have been caused by your script in combination of other errors on my computer. But other than that your script is great and gives windows 10 vibes.

**Comment by Scrut1ny** [comment]
You're all good man, just glad to hear the script makes Windows a little bit better of a experience. I still don't know what would be really causing you this stuff. My headphones work great with the pairing process etc.
